bowling.rbを追加
nkhkcat/ruby-practices pull request #3
Opened 2023-10-03 14:57 UTC by nkhkcat

ボウリングのスコア計算プログラムを追加しました。

2023-10-10 15:27 UTC, u1tnk requested changes
変数名だけ考えてみてください 💪

2023-10-10 15:27 UTC, u1tnk commented on 03.bowling/bowling.rb
> +add_strike_point = 0
動詞から始まると「メソッドかな？」って思っちゃうので、変数と分かる名前にした方が良いかと思います。

2023-10-10 15:27 UTC, u1tnk commented on 03.bowling/bowling.rb
> +      add_strike_point += frames[i + 1][0]
10フレでストライク連続のときに動くかな？と思ったけど、その場合は仮想的な11フレームなどが発生するから問題無いわけですね。
ちょっとスッキリしませんが、仕様の範囲で問題は無いので良しとします。オブジェクト指向版では工夫して欲しいなと思いました。

2023-10-11 00:34 UTC, nkhkcat commented
@u1tnk 
変数名を修正しましたので、ご確認お願いします！

2023-10-11 15:42 UTC, u1tnk approved these changes
はい、問題無いです！
他の例としては
`additional_strike_point`/ `bonus_strike_point` とかでしょうか。参考まで。

2023-10-12 00:27 UTC, merged